[package]
name = "fhf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
git2 = "0.18.3"
rayon = "1.10.0"
walkdir = "2.5.0"
